// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://jcmovytbcghvvukaszyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjbW92eXRiY2dodnZ1a2FzenliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAzMTM1MzksImV4cCI6MjA4NTg4OTUzOX0.Iwcm9SHz8OT3xicgB_iMCqz1HHZg1SGJQnG8Xok8K0E";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);